{"name": "Unsuccessful login with invalid credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'page'\n", "trace": "  File \"c:\\Development\\PycharmProjects\\pw_cuc_py\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"c:\\Development\\PycharmProjects\\pw_cuc_py\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\login_steps.py\", line 6, in step_open_login_page\n    context.login_page = LoginPage(context.page)\n                                   ^^^^^^^^^^^^\n  File \"c:\\Development\\PycharmProjects\\pw_cuc_py\\.venv\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given the user is on the login page", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'page'\n", "trace": "  File \"c:\\Development\\PycharmProjects\\pw_cuc_py\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"c:\\Development\\PycharmProjects\\pw_cuc_py\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\login_steps.py\", line 6, in step_open_login_page\n    context.login_page = LoginPage(context.page)\n                                   ^^^^^^^^^^^^\n  File \"c:\\Development\\PycharmProjects\\pw_cuc_py\\.venv\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "start": 1749363506509, "stop": 1749363506511}, {"name": "When the user logs in with username \"invalid_user\" and password \"wrong_password\"", "status": "skipped", "start": 1749363506512, "stop": 1749363506512}, {"name": "Then an error message \"Epic sadface: Username and password do not match any user in this service\" should be displayed", "status": "skipped", "start": 1749363506512, "stop": 1749363506512}], "start": 1749363506508, "stop": 1749363506512, "uuid": "fc393942-3729-405a-8efd-65f26bf50d54", "historyId": "2355567c2d7d263f2f491558850b28c9", "fullName": "Login: Unsuccessful login with invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}